# Content for the Riarh change-log doc. Functions injected by _make_change_doc.py:
# title, h1, h2, p, b, item(status, text)  where status in {'DONE','PENDING'}

title("Riarh Group Website — Change Log & Handover Review")
p("Prepared by ZippyScale for Dal Riarh. Every change requested by Dal and Ameya, across all three shared files (Dal's remarks, Ameya's audit, and the project photo pack) plus email, with current status. Tick each box as you review it.")
p("Live review build: https://sandy-zippy.github.io/riarh-group/")
p("Design reference (original site): https://whole-interaction-310969.framer.app/")

p("Email check: both website-change email threads (20 May and 1 Jun 2026) were reviewed. All granular instructions live in the two attachments (Dal's Notes and Ameya's audit), both fully reflected below. No change request exists in the emails beyond these.")

h2("How to use this document")
b("Each line is a change that was requested. Green “Done” = built and verified on the live review build. Amber “Pending” = needs a decision or data from your side (it cannot be finished without you).")
b("Use the checkboxes to sign off each item as you confirm it on the live site.")

h2("Summary")
b("All buildable changes from Dal's notes, Ameya's audit, the photo pack and email are complete and verified across desktop, tablet and mobile.")
b("Remaining items are owner decisions / data only (grammar sign-off, team member names, some sqft figures, an optional stat, and font licensing).")

h1("1. Global, Brand & Navigation")
item("DONE", "Renamed “Riarh Construction Group” to “Riarh Group” everywhere (Dal).")
item("DONE", "Navigation label unified to “Who We Are” (was “About Us” in the nav and “Who We Are” in the footer) (Ameya).")
item("DONE", "Removed leftover Framer template junk from the nav (the Product and Resources menu blocks).")
item("DONE", "Added phone number 604-644-4120 prominently, click-to-call, in the header and footer (Dal + Ameya).")
item("DONE", "Made the “years in business” figure consistent at 15+ everywhere (the original said 15 in the copy but 12+ in the stats) (Ameya + Dal).")
item("DONE", "Removed all em/en dashes from the copy.")
item("DONE", "Removed all exact street addresses from the site (Dal).")
item("DONE", "Removed all residential content and the stray residential page (Dal).")
item("DONE", "Set the geographic focus to “Western Canada” (Dal: focus area Western Canada for now).")
item("DONE", "Full grammar and spelling pass across all copy (hyphenation, comma splices, possessives, Oxford commas).")
item("DONE", "Per-page browser/tab titles set for every route; the original's incorrect Contact title (“Your Real Estate Partner”) and generic page titles are gone (Ameya).")

h1("2. Home Page")
item("DONE", "Hero headline changed to “Your commercial vision. Built on time, built right.” (Ameya).")
item("DONE", "Hero sub-headline rewritten to the blueprint-to-walkthrough copy (Ameya).")
item("DONE", "Welcome section replaced “Unparalleled passion. Unmatched results.” with a specific trust statement (100,000+ sq ft across BC, verticals, managed under one roof) (Ameya).")
item("DONE", "Stats bar shows 100K+ / 50+ / 15+ with a count-up animation (Ameya).")
item("DONE", "Why Choose Us reframed to client outcomes: “Your build, done right” / “One team, start to finish” / “Built on 15+ years of commercial experience” (Ameya).")
item("DONE", "The Riarh Approach renamed and de-jargoned: Consult / Plan / Build / Care (removed “Pre-Con” and “Construct”) (Ameya + Dal).")
item("DONE", "Featured project cards now carry a one-line scope and sector context (Ameya).")
item("DONE", "Added the CTA micro-line “Book a free 30-minute project consultation. No commitment.” (Ameya).")
item("DONE", "Footer phone added and “Inquire Today” changed to “Start Your Project” (Ameya).")
item("DONE", "Home hero image swapped to a real Riarh build per Dal's “Change Image” note.")
item("DONE", "Design polish: Why-circles now merge into one single circle; Approach cards have a scroll-zoom reveal; the Our Mission photo arc assembles cleanly.")

h1("3. About / Who We Are")
item("DONE", "Hero rewritten to “Built from the most demanding environment in construction, healthcare…” (was “The Evolution of Excellence”) (Ameya).")
item("DONE", "Kept the “Origin of Precision” healthcare story (Ameya called it the best copy on the site).")
item("DONE", "Stats made consistent at 15+ (Ameya).")
item("DONE", "Expanded Dal's bio (Ameya).")
item("DONE", "Added Dal's headshot to the leadership section (Ameya flagged this as a critical trust gap).")
item("DONE", "Kept the tagline “We build relationships first. The structures follow.” (Ameya).")
item("DONE", "Fixed the Innovation jargon: “VDC (Virtual Design)” became “3D virtual design and modern building science…” (Ameya + Dal).")
item("DONE", "About hero banner image changed and enlarged so it reads as a proper banner (Dal).")
item("DONE", "Resolved the “Image Distorted” flags on the leadership and ethos images (now cropped, not stretched) (Dal).")
item("PENDING", "Add 2-3 named team members with roles (Ameya recommendation) — needs real names from you; we will not invent people.")

h1("4. Commercial Page")
item("DONE", "Hero changed to “Commercial builds that open on time, look the part, and hold up for the long run.” (Ameya).")
item("DONE", "Added a Portfolio section with categories Commercial / Industrial / Tenant Improvements, with Tenant Improvements promoted (Dal + Ameya).")
item("DONE", "Project gallery cards show a sector tag and scope (Ameya).")
item("DONE", "“What We Do” changed from “Building for Business Success” to “We build the commercial spaces that keep businesses running.” with new sub-copy (Ameya).")
item("DONE", "Built “The Riarh Standard” section.")

h1("5. Services Page")
item("DONE", "Planning / Designing / Construction phases present and on-brand (Dal).")
item("DONE", "Resolved the “Distorted Images (all 3)” flag on the phase images (Dal).")
item("DONE", "Services CTA image changed per Dal's “Change Image” note.")
item("DONE", "Removed the “mandates / expert execution” jargon from the Services hero sub-headline and the repetitive all-caps “Book a consultation now!” CTAs (Ameya).")
item("PENDING", "Optional: Ameya suggested replacing the “The Science of Building” Services headline with a more direct line. The editorial headline was kept (it matches the reference) and the jargon removed. Confirm your preference.")

h1("6. Projects & Photos (from the photo pack)")
item("DONE", "Renamed and relocated: 45 Broadway → Broadway Towers (Vancouver); Rainbow Daycare → Sunshine Rain Daycare (Surrey); Industrial Warehouse → Fresh Haul Logistics (Surrey / Langley); Happy Valley Pharmacy → Happy Prairie Pharmacy (Edmonton); Flatiron Loft → Ignis Gale Engineering Office (Calgary); 125 Park Ave → Law Firm (Vancouver) (Dal).")
item("DONE", "Added new projects: Medico Head Office (South Surrey), Riarh Group HQ (Vancouver), Mortgage Offices (White Rock) (Dal).")
item("DONE", "Added Woodland Vet, sourced from medicoconstruction.com (Dal: project to add).")
item("DONE", "Kept both Mucho Burrito locations distinct (Abbotsford and Burnaby).")
item("DONE", "Ordered each project's photos front-of-house to back-of-house, as requested (Dal).")
item("DONE", "Used only images from your folders; removed duplicates (Dal).")
item("DONE", "Processed 131 photos, built a dedicated detail page per project, and made every project card deep-link to its gallery.")
item("DONE", "Removed the CEO's Message page entirely (Dal: “Remove the page”).")
item("PENDING", "Add square-footage figures to the remaining project cards — only verifiable ones are in so far (Woodland 2,200 sq ft, Smile Plus 2,840 sq ft). Needs your numbers (Ameya).")
item("DONE", "Made the “Change Image” hero picks (home, about, services CTA) from your photo pack — confirm you are happy with the specific shots.")

h1("7. Dal's 18 Annotated Screenshots — coverage")
p("Every red flag on the 18 screenshots is accounted for above; mapped here for completeness.")
item("DONE", "01 Hero “Change Image”; 02 Welcome “Incorrect”; 03 Stats 12 vs 15; 04 Approach rename; 05 About hero “Change Image”; 06 About stats.")
item("DONE", "07 Origin “Western Canada for now”; 08 Relationships “Image Distorted”; 09 Ethos “Image Distorted” + VDC jargon; 10 CEO page “Remove The Page”.")
item("DONE", "11 Commercial hero; 12 Gallery “Western Canada”; 13 Capabilities; 14 The Riarh Standard; 15 Services “Distorted Images (all 3)”; 16 Services CTA “Change Image”; 17 Vet project “Change Image” (Woodland added).")
item("PENDING", "“Rochelle and Marketing Team to confirm grammar” (flagged on screenshots 04, 07, 08, 13) — copy is mechanically clean; needs Rochelle's final blessing.")

h1("8. Still Pending — owner decisions only (not bugs)")
item("PENDING", "Final grammar / copy sign-off by Rochelle and the marketing team.")
item("PENDING", "Named team members for the About page (no real names available).")
item("PENDING", "Square-footage figures for the remaining project cards.")
item("PENDING", "A stronger headline stat than “50+ Units” (e.g. $ value delivered, client return rate, verticals served) — Ameya's optional idea; needs a verified number.")
item("PENDING", "Confirm the specific “Change Image” photo picks for the hero slots, or send replacements.")
item("PENDING", "Resolve font licensing (acid-grotesk) before promoting to a custom domain.")

h1("9. Deployment")
item("DONE", "Deployed to GitHub Pages as a client-review build: https://sandy-zippy.github.io/riarh-group/")
b("Repository: Sandy-zippy/riarh-group (source on the main branch, the built site on the gh-pages branch).")
b("Verified live: all pages and project galleries load, no broken images, no console errors, across desktop, tablet and mobile.")
b("Note: this is a public review URL. Clear the font licensing before pointing a real domain (e.g. riarhgroup.com) at it.")
